Add lolesports data article
CommunityDragon/HexDocs pull request #7
Opened 2020-09-23 19:07 UTC by Canisback

2020-09-23 19:15 UTC, thomasmarton requested changes
One minor change and I'm ready to push the merge button

2020-09-23 19:15 UTC, thomasmarton commented on lol/esportsapi/esports-match-data.md
> +![ACS header](http://canisback.com/images/acs.png)
Since we currently don't proxy the images on our end, we're gonna need an HTTPS URL

2020-09-23 19:35 UTC, Canisback commented
Updated to https, and added a link to the source notebook.

2020-09-24 16:47 UTC, thomasmarton approved these changes

2020-09-24 16:47 UTC, merged