Getting Started With The Riot Games API
CommunityDragon/HexDocs pull request #9
Opened 2020-10-14 21:41 UTC by bangingheads

Article for getting started with the Riot Games API.

2020-10-14 23:09 UTC, thomasmarton requested changes
I'm going to request a few changes to make the document more translator friendly. Amazing work with the layout and the information density tho!

2020-10-14 23:09 UTC, thomasmarton commented on lol/riotapi/getting-started-with-the-riot-games-api.md
> +Platform routing is used for a League of Legends endpoints other than the Tournament API endpoints.
"for a League of Legends endpoints"
I feel like a better version of this would be something along the lines of: "Platform routing is used for all League of Legends endpoints with the exception of the Tournament API"

2020-10-14 23:09 UTC, thomasmarton commented on lol/riotapi/getting-started-with-the-riot-games-api.md
> +The Riot API accepts your API key via headers. This is the cleaner method to authenticating.
to authenticate*

2020-10-14 23:09 UTC, thomasmarton commented on lol/riotapi/getting-started-with-the-riot-games-api.md
> +**PUUID:** Globally unique ID of an account.
I think you have to have an extra linebreak for these to appear correctly

2020-10-15 00:15 UTC, thomasmarton commented
I'm going to have to leave the PR as is for now as we found some visual issues with the markdown, I'll sit down with Ray to figure out what it might be

2020-10-18 18:15 UTC, Hi-Ray commented
What's the issue?

2020-10-22 21:28 UTC, thomasmarton approved these changes

2020-10-22 21:29 UTC, merged